### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#16]
We need to add the footer. The background of the footer will be black and font size will be white. 
Add the text `Hacktoberfest 2022` in the footer.
Make sure the footer is responsive across all devices.

**Comment by shivanidotcom** [comment]
Hi please assign me this task

**Comment by Vidhika002** [comment]
Hi..I can add footer .Please assign me this task
