### ISSUE TITLE
Add dark mode 

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#19]
We need to add the dark mode to the site. It will like a toggle, or you can say user can switch between light and dark mode. Make sure all the text is showing clearly when the site is on dark mode

**Comment by Divyanshi2408** [comment]
Hey @ShehrozIrfan  I would like to contribute to this issue  Could you please assign me this issue ?

**Comment by ShehrozIrfan** [comment]
@Divyanshi2408 
Assigned.

**Comment by Divyanshi2408** [comment]
Will this contribution  be added to Hacktoberfest?
