### ISSUE TITLE
Add bootstrap columns and classes to the footer

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#27]
We need to add the bootstrap classes to the footer as we've for the whole page. We need to add the `row` and `columns` and make sure it is responsive on all screens.

**Comment by m-mishra2001** [comment]
will you please assign this task @ShehrozIrfan

**Comment by m-mishra2001** [comment]
![image](https://user-images.githubusercontent.com/60498472/194704551-e56a1bc6-9ec6-4f0c-878d-952024d69758.png)

Is this ok @ShehrozIrfan

**Comment by ShehrozIrfan** [comment]
@m-mishra2001 
Looks good. Just one questions: Where the links redirects to? Like on clicking twitter, linkedin, fb icons where it will take?
And one update:
Change the text copyright text to `copyright © 2022`

**Comment by m-mishra2001** [comment]
Currently I haven't added links 
If you provide me the links I gonna add it or else should I remove these icons ?

**Comment by m-mishra2001** [comment]
Okk I gonna edit copyright text

**Comment by ShehrozIrfan** [comment]
> Currently I haven't added links If you provide me the links I gonna add it or else should I remove these icons ?

ohh.. For now we can remove the icons.

**Comment by m-mishra2001** [comment]
Okk 👍

**Comment by m-mishra2001** [comment]
![image](https://user-images.githubusercontent.com/60498472/194715440-a65252cf-1694-4981-9783-b4db94777f9c.png)

![image](https://user-images.githubusercontent.com/60498472/194715529-08f946c7-e270-4081-b83d-31f7e214fc63.png)

is it ok @ShehrozIrfan i have uploaded 2 screen shots over here

**Comment by ShehrozIrfan** [comment]
@m-mishra2001 
Good Work.
I think all the text should be centered like this: `First Contribution Hactoberfest 2022 List © 2022`
