### ISSUE TITLE
I want to Contribute for Hacktoberfest

### ISSUE THREAD

**Issue by minhaj-313** [ShehrozIrfan/hacktoberfest-2022-first-contribution#3]

**Comment by ShehrozIrfan** [comment]
Hi @minhaj-313 
You can contribute to hacktoberfest.
Please follow the guidelines in the readme file, and make your first contribution.
Have fun!

**Comment by minhaj-313** [comment]
> Hi @minhaj-313 You can contribute to hacktoberfest. Please follow the guidelines in the readme file, and make your first contribution. Have fun!

Ok Sure, Thanks, Please Assign me

**Comment by ShehrozIrfan** [comment]
@minhaj-313 
Please do follow the readme file. No need to assign. Just follow the readme file and you're good to go!

**Comment by minhaj-313** [comment]
> @minhaj-313 Please do follow the readme file. No need to assign. Just follow the readme file and you're good to go!

Complited : Please Merge My PR, I Follow readme rules.
labeled as hacktoberfest-accepted please

**Comment by ShehrozIrfan** [comment]
@minhaj-313 
Hey!
Please share your PR link.

**Comment by minhaj-313** [comment]
https://github.com/minhaj-313/hacktoberfest-2022-first-contribution

**Comment by minhaj-313** [comment]
https://github.com/minhaj-313/hacktoberfest-2022-first-contribution/commit/855dff611adb6fa10b0b0182f76f9b9eb66f9893
