### ISSUE TITLE
Update the dark mode to set dark color for all the elements.

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#30]
Currently, we've dark mode in our site. When it is applied, the footer color and the dark mode color doesn't match. Also the github icon is not visible in dark mode. We need to make following fix when dark mode is on:
- Github icon is visible.
- Make the footer color same as we've the body background color.

**Comment by Abhinav-3359** [comment]
Sir pls assign this issue to me
