### ISSUE TITLE
Add toggler button for dark and light mode.

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#31]
We need to add the toggler button, which switches the dark mode to light and vice versa.
We need to add something like this: [Dark mode toggler](https://res.cloudinary.com/dtpseup2f/image/upload/f_auto,q_auto/v1605457705/letsbuildui/2020-11-15-toggle/toggle-complete.gif)

**Comment by jainpatel25** [comment]
can I try to add a toggle button?

**Comment by ShehrozIrfan** [comment]
@jainpatel25 
Assigned.

**Comment by ShehrozIrfan** [comment]
@jainpatel25 
We need to add something like this: [Dark mode toggler](https://res.cloudinary.com/dtpseup2f/image/upload/f_auto,q_auto/v1605457705/letsbuildui/2020-11-15-toggle/toggle-complete.gif)

**Comment by jainpatel25** [comment]
Ohk i understand I will do it and can my pr will get hactoberfest tag

**Comment by ShehrozIrfan** [comment]
@jainpatel25 
Yes, it will get `hacktoberfest-accepted` tag when your PR got merged. 
Meanwhile you can follow me and star this repo for further updates.
Thanks.

**Comment by jainpatel25** [comment]
hey I complete a task

**Comment by rajatrai30** [comment]
hello @ShehrozIrfan 
you can assign this task to me.
because I have done work on that

**Comment by ShehrozIrfan** [comment]
@rajatrai30 
Assigned.
Have fun!

**Comment by rajatrai30** [comment]
Thank you😃
