### ISSUE TITLE
Update the style of footer 

### ISSUE THREAD

**Issue by Hariom8799** [ShehrozIrfan/hacktoberfest-2022-first-contribution#35]
Style of footer is different from the whole website template

**Comment by Hariom8799** [comment]
pls assign me this issue

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
Would you please elaborate in detail what changes you want to make?

**Comment by Hariom8799** [comment]
Bro your footer template is so different if it was like a style which you use in header then it will be better than now

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
ohh okay. Actually, someone is already working on the footer styles. 
So, we need to wait for that changes and then see what we need to update.

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
Assigned.
Make the footer. Super good!

**Comment by Hariom8799** [comment]
why not bro, I will do the work by tomorrow

**Comment by ShehrozIrfan** [comment]
Sure.
You can star this repository for further updates!

**Comment by Hariom8799** [comment]
done
