### ISSUE TITLE
Add contributor label to readme

### ISSUE THREAD

**Issue by Hariom8799** [ShehrozIrfan/hacktoberfest-2022-first-contribution#36]
![Capture](https://user-images.githubusercontent.com/76242202/194708300-885dd1b5-be55-4a42-930d-9638ad3510f6.PNG)
like that

**Comment by Hariom8799** [comment]
pls assign me this issue

**Comment by ShehrozIrfan** [comment]
@Hariom8799 
Assigned.

**Comment by Hariom8799** [comment]
pls add the hacktoberfeast label
