### ISSUE TITLE
Adding Dynamic feature

### ISSUE THREAD

**Issue by Prabal-Jain** [ShehrozIrfan/hacktoberfest-2022-first-contribution#46]
We can make this page more dynamic and attractive by parallax.

**Comment by Prabal-Jain** [comment]
Please assign this issue to me

**Comment by ShehrozIrfan** [comment]
@Prabal-Jain 
- Please make sure to keep the code clean.
- Don't add any extra lines.
- Put all the css in `assets/css/`
And when you're done, first share the image or video for demonstration!

Have fun!
