### ISSUE TITLE
Update github icon color in dark mode.

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#66]
Currently, when dark mode is enabled, the `github` icon doesn't seem clear. Because it's color is black, and when dark mode is applied it is almost hidden. So, we need to update the icon color in dark mode so that it is visible. You can choose the color of your choice, but make sure it looks good with the site overall theme.

**Comment by manav-06** [comment]
@ShehrozIrfan please assign this to me

**Comment by ShehrozIrfan** [comment]
@manav-06 
Assigned.

**Comment by Arkapro1** [comment]
After reading the guidelines I am soo excited to contribute here please assign me the task 😀

**Comment by ShehrozIrfan** [comment]
@Arkapro1 
Assigned.
Have fun!

**Comment by manav-06** [comment]
@ShehrozIrfan please review #74
