### ISSUE TITLE
Improve footer and change box shadow

### ISSUE THREAD

**Issue by radhika141** [ShehrozIrfan/hacktoberfest-2022-first-contribution#72]
Pls assign this issue to me!

**Comment by ShehrozIrfan** [comment]
@radhika141 
Assigned.
Have fun!

**Comment by Arkapro1** [comment]
please assign me the task 😀

**Comment by Atharvasaraiya** [comment]
im new here..can you assign me this tast?

**Comment by ShehrozIrfan** [comment]
@Arkapro1 
Assigned.

**Comment by ShehrozIrfan** [comment]
@Atharvasaraiya 
Assigned.

**Comment by Arkapro1** [comment]
please add the hacktoberfest-2022 tags for this issue

**Comment by Harshit-2112** [comment]
Please assign this to me, Want to make some changes in Footer with font awesome class.
