### ISSUE TITLE
Update style of search bar in dark mode

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/hacktoberfest-2022-first-contribution#76]
Currently, when the dark mode is enabled, the search bar remains white and is not looking good. Because the dark mode is applied and search bar remains white. 
So, we need to update the style of the search bar such that when the dark mode is enable, it's color is also adjusted according to the dark mode, make sure any color you use looks good with the dark mode.

**Comment by Abhishek3223** [comment]
hey can i work on this??

**Comment by Arkapro1** [comment]
Great! I want to contribute here also,, please can you assign me the task?

**Comment by akrishna777** [comment]
I have found a solution to change color of input in dark mode. I can correct it. I have written the code. Let me make a pull request for this.

**Comment by Arkapro1** [comment]
please me to find out what was going wrong
![image](https://user-images.githubusercontent.com/100460957/195318459-98507ed6-d803-4f06-b493-e9ce8b032378.png)

**Comment by ShehrozIrfan** [comment]
@Arkapro1 
I was really surprised to see this, please do let visit the hactoberfest site and let us know is there any guideline we're not following?
